### ISSUE TITLE
Long text in the code block makes the content overflow

### ISSUE THREAD

**Issue by rajat1saxena** [codelitdev/courselit#97]
For example:

This content in the mobile resolution overflows the page.

```
webapp:
 volumes:
   - uploads:/uploads
volumes:
 uploads:
   driver: local
   driver_opts:
     device: /c/Users/<your_name>/apps/uploads
     o: bind
```
